### ISSUE TITLE
Broken favicon on other protocols

### ISSUE THREAD

**Issue by NomarCub** [joethei/obsidian-link-favicon#3]
Links with protocols other than http/https (such as file:, obsidian:, mail:) have broken favicons.
Happens only when there's already domains in the ignored list.

Source mode:
![image](https://user-images.githubusercontent.com/5298006/147790328-6cb14037-792f-45f4-843a-e3eac51c11c7.png)
Live preview:
![image](https://user-images.githubusercontent.com/5298006/147790359-0642feb0-491c-45bc-b016-c75a6316e2fa.png)
Reading:
![image](https://user-images.githubusercontent.com/5298006/147790378-715ccbd9-648f-4e57-85ed-e615b9659389.png)

Code:
```md
[local](file:///D:/Downloads)
[vscode](vscode://file/D:/Downloads)
[obsidian](obsidian://vault/notes)
user@example.com
[normal site](https://discord.com/)
```

**Comment by joethei** [comment]
Could you verify that this issue no longer exists in v1.4.1?

**Comment by NomarCub** [comment]
It's still broken.

**Comment by joethei** [comment]
I cannot reproduce this issue, please check that this still happens in a clean vault?

- Do you use the _Icon Shortcodes_ plugin and/or the Integration this plugin provides with that one?
- Which version of this plugin are you on?
- Are you on desktop or mobile?
- What is your configuration?

**Comment by NomarCub** [comment]
I can reproduce this 100%.
I'm on Windows.

1. Open the Help vault from the sidebar. (This opens a fresh vault every time.)
2. Install the plugin.
3. Add anything to the plugin's ignored domain list.
4. Paste the text above, see that they have broken icons.

**Comment by joethei** [comment]
Huh, I thought I already tried that.😤
Issue should now be fixed.

**Comment by kazerniel** [comment]
> Huh, I thought I already tried that.😤 Issue should now be fixed.

@joethei Hi, I'm still encountering this bug, reproducible in a sandbox vault, even without putting any domains in the exclusion list. I'm using this link format: `[spreadsheet](<file://d:\path with spaces\file name with spaces.xlsx>)`

![Image](https://github.com/user-attachments/assets/5d01be50-aa60-46f1-94ed-c6903ca836e0)

Edit: This started happening quite recently, previously links to local files didn't try to display a favicon.
