### ISSUE TITLE
Icons don't load in live preview

### ISSUE THREAD

**Issue by NomarCub** [joethei/obsidian-link-favicon#47]
It happens regularly, and not just on the end of notes, as can be seen on the GIF. It was not easy to reproduce, it seemed to depend on window size, the number and kinds of links. Here's the text with which I could reproduce consistently: https://pastebin.com/f8J9pK4z.
In the GIF, I open and close the note with Ctrl + W and Ctrl + Shift + T.
![favicons](https://user-images.githubusercontent.com/5298006/193448099-ee0007f0-313f-4ae4-b36e-94658df91290.gif)

**Comment by jpfieber** [comment]
I'm running 1.1.15. I just found and installed this plugin, and found it won't show any favicons in the live preview, but they show up fine in reading mode. I restarted Obsidian, same result.

**Comment by hidegh** [comment]
Thanx @jpfieber , so basically an useless plugin then?!

**Comment by NomarCub** [comment]
It works fine for me for the most part, no change with v1.1.15, just checked the sandbox vault too. @jpfieber under what conditions does this happen? What platform are you on? Have you tried the sandbox vault?

**Comment by jpfieber** [comment]
I'm on Windows. It happens to every external link on any page. This is the first time I've heard of the 'Sandbox Vault'. I just tried it and it works properly there.  I'm guessed that meant it could be a clash between plugins. I disabled every community plugin except this one, closed Obsidian, opened it and it still doesn't work.  That leaves me thinking it's either related to a core plugin, core plugin setting, or general Obsidian setting. What should I try next?

**Comment by NomarCub** [comment]
You should try copying the .obsidian config folder (with the other plugins disabled) to a new vault. It might be the settings you mentioned, CSS snippets, or possibly some vault level Obsidian cache that isn't stored in the vault itself.

**Comment by jpfieber** [comment]
Tried that, got nowhere. Tried creating a brand new vault and adding only Link Favicons, no other plugins, no changes to any settings, still doesn't work. Only seems to work in the sandbox vault.  What's the difference between a default new vault and a sandbox vault?  Seems my default new vault is somehow not default or this would be not working for others as well...

**Comment by NomarCub** [comment]
You can try installing Obsidian with a fresh installer, as old installs can have older Electron versions. Maybe reinstall it completely and delete appdata and localappdata. Beyond that I'm out of ideas. I also had weird vault specific problems with this plugin in the past.

**Comment by ChristinWhite** [comment]
I'm having the same issue and am having a really difficult time tracking it down.

macOS: 13.2 (22D49)
Obsidian: 1.1.15
Link Favicons: 1.8.1

So here's the weird thing:
- Delete Obsidian and it's Application Support folder and preferences .plist. Reinstall. Open my main vault, reload. It doesn't work ❌ 
- Open the sandbox vault, paste in my test note, enable plugins and install Link Favicons. It works ✅ 
- Replace `.obsidian` from my vault into the sandbox vault. It doesn't work ❌ 
- Make zero other changes and reload: It works ✅ and keeps working after subsequent reloads.

It doesn't look like it's a plugin or snippet incompatibility. I've turned off all snippets in my main vault and it makes no difference. I haven't gone through each plugin but since they all work in the sandbox vault I'm at a loss for why they work there and not in my vault. 

No console errors either.

**Comment by ChristinWhite** [comment]
Did a little more digging and I'm even more confused about what's going on. For reference, my main vault is named _Launch Control_.

- I deleted everything in the sandbox vault. I then copied everything from _Launch Control_ into the sandbox vault, except `.trash`.
- I renamed _Launch Control_ to _Backup_ and copied the sandbox vault into my vaults folder. I renamed it _Launch Control_, opened it up in Obsidian and favicon links work. 
- Just to test things, I went back to _Backup_ and deleted `.trash`, it's still broken. 

The two vaults should be basically identical but for some reason Link Favicons works on one and not the other.

**Comment by NomarCub** [comment]
The issue doesn't seem to be specific to live preview. I tried this plugin: https://github.com/KosmosisDire/obsidian-webpage-export, which exports using reading view. Favicons are really spotty in the exported HTML, and are missing like half the time.

**Comment by guihasparyk** [comment]
If it worked would be awesome!

I would love this feature because I transitioned my research sessions and bookmarks from Firefox Bookmarks to Obsidian and would be better visually to see icons of each bookmark.

**Comment by joethei** [comment]
I've released a new version that should fix some issues reported here.
It looks to me like some of you experience a different issue from the one NomarCub is facing.
I've fixed the issue of favicons not showing up in live preview at all in some vaults.



> The issue doesn't seem to be specific to live preview. I tried this plugin: https://github.com/KosmosisDire/obsidian-webpage-export, which exports using reading view. Favicons are really spotty in the exported HTML, and are missing like half the time.
For this issue I am not sure if that is caused by my plugin or the export plugin.

**Comment by guihasparyk** [comment]
It's working like a charm. You are amazing! Thanks @joethei 👍

**Comment by NomarCub** [comment]
Thanks for the fixes!
However, this issue is still not fixed indeed.
It's been a while, and it wasn't even clear to me, so I updated the first comment with a more explicit repro.
